# Generated by Django 5.2.17 on 2026-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentschedule',
            options={'ordering': ['student__id', models.Case(models.When(then=models.Value(0), time_slot__day='Mon'), models.When(then=models.Value(1), time_slot__day='Tue'), models.When(then=models.Value(2), time_slot__day='Wed'), models.When(then=models.Value(3), time_slot__day='Thu'), models.When(then=models.Value(4), time_slot__day='Fri'), models.When(then=models.Value(5), time_slot__day='Sat'), models.When(then=models.Value(6), time_slot__day='Sun'), default=models.Value(7), output_field=models.IntegerField()), 'time_slot__start_time']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': [models.Case(models.When(day='Mon', then=models.Value(0)), models.When(day='Tue', then=models.Value(1)), models.When(day='Wed', then=models.Value(2)), models.When(day='Thu', then=models.Value(3)), models.When(day='Fri', then=models.Value(4)), models.When(day='Sat', then=models.Value(5)), models.When(day='Sun', then=models.Value(6)), default=models.Value(7), output_field=models.IntegerField()), 'start_time']},
        ),
    ]
