# Generated by Django 5.2.17 on 2026-09-30 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_unique_slot_per_day_start'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='semester',
            field=models.CharField(blank=True, help_text="Semester (e.g., '1st Sem').", max_length=50),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Section code (e.g., A, B, 1A).', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=40, help_text='Maximum number of students in this section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, help_text='Faculty handling this section.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_taught', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='The subject this section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='subjects.subject')),
            ],
            options={
                'ordering': ['subject__code', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section of the subject being taken.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.section'),
        ),
    ]
