# Generated by Django 5.2.17 on 2026-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_purge_invalid_terms'),
        ('students', '0002_student_enrolled_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students taking this section.', related_name='sections', to='students.student'),
        ),
    ]
