# Generated by Django 5.2.17 on 2026-09-26 00:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Numerical score between 0.00 and 100.00.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Score cannot be below 0.'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='Score cannot exceed 100.')])),
                ('letter', models.CharField(editable=False, help_text='Auto-computed letter grade (A, B, C, D, F).', max_length=2)),
                ('grade_points', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-computed grade points (4.00, 3.00, 2.00, 1.00, 0.00).', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User (Admin or assigned Teacher) who recorded this grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student receiving this grade.', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('subject', models.ForeignKey(help_text='The subject for which this grade is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subjects.subject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
