# Generated by Django 5.2.17 on 2026-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Auto-computed grade points (1.00=best, 3.00=pass, 4.00=incomplete, 5.00=fail).', max_digits=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(editable=False, help_text='Auto-computed University of Antique grade (1.00, 1.25, ..., 5.00).', max_length=5),
        ),
    ]
