# Generated by Django 5.2.17 on 2026-09-30 16:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_recompute_grade_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_incomplete',
            field=models.BooleanField(default=False, help_text='Subject not completed yet. Recorded as INC with no grade points.'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-computed grade points (1.00=best, 3.00=pass, 5.00=fail). Empty for INC.', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(editable=False, help_text='Auto-computed grade (1.00, 1.25, ..., 5.00, or INC).', max_length=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numerical score between 0.00 and 100.00. Leave empty for INC.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Score cannot be below 0.'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='Score cannot exceed 100.')]),
        ),
    ]
