# Generated by Django 5.2.17 on 2026-10-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_convert_incomplete_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='manual_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade points entered directly by staff, overriding the score bands. Use this to record a grade the scale has no band for.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='remark',
            field=models.CharField(blank=True, help_text='Optional note, e.g. a reason for a manual grade.', max_length=255),
        ),
    ]
