# Generated by Django 5.2.17 on 2026-09-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this student is currently enrolled in.', related_name='enrolled_students', to='subjects.subject'),
        ),
    ]
