# Generated by Django 5.2.17 on 2026-10-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_enrolled_subjects'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='students.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Optional subject this thread is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='subjects.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
                'unique_together': {('student', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, help_text='When the other participant read this message.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='students.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('school_year', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why the student wants this subject.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who approved or rejected the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollment_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who made the request.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='students.student')),
                ('subject', models.ForeignKey(help_text='Subject the student wants to take.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='subjects.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'subject', 'semester', 'school_year'), name='unique_pending_enrollment_request')],
            },
        ),
    ]
