# Generated by Django 5.2.17 on 2026-10-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_messagethread_message_enrollmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='algorithm',
            field=models.CharField(default='AES-GCM-256', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='ciphertext',
            field=models.TextField(blank=True, default='', help_text='Base64 AES-GCM ciphertext of the message body.'),
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(blank=True, default='', help_text='Base64 initialisation vector used for this message.', max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Deprecated. Messages are stored as ciphertext; use ciphertext and iv. Kept only so older rows can still be rendered.'),
        ),
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField(help_text='Base64 raw public key, generated in the browser with Web Crypto.')),
                ('algorithm', models.CharField(default='ECDH-P256-HKDF-SHA256-AESGCM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
